completed prep-html-script-tag
mahdiehmaleki96/javascript-prep-0624-code-solutions pull request #3
Opened 2024-06-16 04:02 UTC by mahdiehmaleki96

![Screenshot](https://github.com/mahdiehmaleki96/javascript-prep-0624-code-solutions/assets/123231424/57ea8578-19f4-4697-8965-fa3b0632e6f9)

2024-06-17 16:22 UTC, shawnkost requested changes
Code looks good Mahdieh, just need to answer the quiz questions!

2024-06-17 16:22 UTC, shawnkost commented on prep-html-script-tag/prep-html-script-tag-quiz-notes.md
> +
Don't forget to answer the quiz questions!

2024-06-19 00:17 UTC, mahdiehmaleki96 commented on prep-html-script-tag/prep-html-script-tag-quiz-notes.md
> +- What tag is needed to load JavaScript scripts into an HTML document?
<script>

2024-06-19 00:17 UTC, mahdiehmaleki96 commented on prep-html-script-tag/prep-html-script-tag-quiz-notes.md
> +- How do you use a script tag to write JavaScript directly in the HTML document?
When the script is internal, it is placed directly between <script> and </script>.
<script>
</script>

2024-06-19 00:17 UTC, mahdiehmaleki96 commented on prep-html-script-tag/prep-html-script-tag-quiz-notes.md
> +- How do you use a script tag to load an external JavaScript file?
For external scripts, the src attribute specifies the URL of the external script file.
<script src="script.js"></script>

2024-06-19 15:57 UTC, shawnkost approved these changes
👍🏻

2024-06-20 17:36 UTC, merged